### ISSUE TITLE
Why drop PHP 7.0 support?

### ISSUE THREAD

**Issue by leonboot** [sonata-project/SonataUserBundle#1004]
Today, the CI builds of our project started to fail. Reason for this was that the `add_support_for_fos_user2` branch disappeared from this repository.

"Wait, you were actually using a dev branch for your project?"

Yes. We needed FOSUserBundle 2 for our project and also use Sonata. Browsing the issues of this repository back then, we saw that FUB2 support was on the radar and trusted that, by the time our project was finished, a version with FUB2 support would be officially released.

Today, because the dev branch had disappeared, we checked and saw the 4.0 release with FUB2 support. Yay! But after running the `composer require` command, the enthousiasm soon faded. Our project runs on PHP 7.0. Our hosting provider only uses official packages provided by the OS vendor, which would be PHP 7.0 for Ubuntu 16.04 LTS. This leaves us in an impasse, since 4.0 has a hard requirement on 7.1.

I've seen a lot of discussion about this in closed issues. I was rather disappointed about the "Too bad, 7.0 is EOL" comments. First of all, security updates continue up until December 3rd. And second, a lot of us don't have the luxury of upgrading to 7.1. The next LTS version for Ubuntu is due in April. I expect this version to be shipped with at least PHP 7.1. But een then, I can imagine that our hosting provider will not perform a release upgrade before the first maintenance release for the new LTS is released.

And as long as none of the code has any real benefit from 7.1 features (what value do the void return types add to the code?) I don't believe it's fair to enforce 7.1 while 7.0 compatibility will run the code just fine.

I am now forced to fork this repo and remove the void types and lower the php requirement in the composer.json for my project, which means I'm going to have to maintain my fork when this repository gets new releases. I don't really look forward to this, I'm sure you understand.

**Comment by Soullivaneuh** [comment]
> First of all, security updates continue up until December 3rd

2.0 was unstable. We only keep minimum support for actively maintained PHP versions, not security. Since 2.0 is now stable, PHP 7.1 will still be the minimum until security release support is ended.

> And second, a lot of us don't have the luxury of upgrading to 7.1. The next LTS version for Ubuntu is due in April.

Unfortunately, this is not our issue. We just can't support all OSs constraints. We strictly follow the PHP roadmap and only this one.

Please see our contributing guide about this part: https://github.com/sonata-project/SonataUserBundle/blob/4.x/CONTRIBUTING.md#dependency-changes

Sorry, but we can't start to make exceptions for that.

Last words: You said you was using `add_support_for_fos_user2` which was dropped. Please remember that at the moment you leave a stable release match to a dev branch, you are on a unstable environment and you did it with your own risks. This is not because PHP 7.0 was supported on this branch that it means it will be on the next release.

At least if you can't upgrade PHP now, you may try to find the commit hash of you `composer.lock` of the last working state of user-bundle and stick at this one.

> I'm sure you understand

We understand, but this won't be fixed . I'm sure you understand your constraints too.

Regards.
