### ISSUE TITLE
Roadmap SonataAdmin 4 / Symfony 5

### ISSUE THREAD

**Issue by konradmichalik** [sonata-project/SonataUserBundle#1453]
## Feature Request

Hey,

is there a roadmap or a plan, when its possible to use the SonataUserBundle with the actual SonataAdmin v4 and Symfony v5.3? 

Thanks!

**Comment by VincentLanglet** [comment]
The master branch is already compatible with Sonata 4.
For Symfony 5, https://github.com/sonata-project/SonataUserBundle/pull/1449 is required since FosUserBundle is not compatible with Symfony 5.

And then, lot of extra work will be needed to have a stable release, like
- Updating the doc
- Bumping phpstan/psalm
- Restricting method/classes
- Removing deprecated code

**Comment by konradmichalik** [comment]
Thanks for the fast reply and the good work. 

Could you estimate a possible release date for a usable development state?

**Comment by VincentLanglet** [comment]
> Could you estimate a possible release date for a usable development state?

Not really. It depends on time we have, and help we get.

**Comment by jordisala1991** [comment]
The 5.x branch is already supporting Sonata 4 and Symfony 5.

Keep in mind that no stable release is done, but help testing it and reporting/fixing bugs is always welcome.

**Comment by konradmichalik** [comment]
Thanks for the fast support, we'll try the branch and will report feedback/fix problems, if we find bugs.
