### ISSUE TITLE
Redirect from login page

### ISSUE THREAD

**Issue by ossinkine** [sonata-project/SonataUserBundle#379]
Why in `SecurityFOSUser1Controller::loginAction` ([link](https://github.com/sonata-project/SonataUserBundle/blob/master/Controller/SecurityFOSUser1Controller.php#L33)) if the user is already authenticated, it redirects to `sonata_user_profile_show`?
First, this route in an application may be not specified.
Secondly, I think the route should depend on the firewall.
For example, in `main_firewall` from URL `/login` should be redirect to `/profile`, but in `admin_firewall` from URL `/admin/login` should be redirect to `/admin`.

**Comment by benglass** [comment]
:+1: The sonata_user_profile_show route name being hard coded as the redirect location if the user is already logged in and tries to access /admin/login should probably be changed to reflect the same logic that is invoked when the user first logs in. They should be redirected to the referrer (if its not the login url) otherwise the admin dashboard.

https://github.com/sonata-project/SonataUserBundle/blob/master/Controller/AdminSecurityController.php#L30

**Comment by MortisQc** [comment]
+1 for Benglass

**Comment by OskarStark** [comment]
:+1:

**Comment by OskarStark** [comment]
Closed via #869
