### ISSUE TITLE
No entity manager defined for class Symfony\Component\Security\Core\User\User (in_memory provider)

### ISSUE THREAD

**Issue by karser** [sonata-project/SonataUserBundle#661]
```
No entity manager defined for class Symfony\Component\Security\Core\User\User
in SonataUserBundle:Admin/Core:user_block.html.twig at line 6
```

Here is how to reproduce this issue:

```
        //Logged as in_memory user
        $tokenStorage = $this->container->get('security.token_storage');
        $token = $tokenStorage->getToken();
        /* @var \Symfony\Component\Security\Core\User\User $user */
        $user = $token->getUser();
        $r = $this->container->get('sonata.user.admin.user');
        $res = $r->id($user);
```

**Comment by enebe-nb** [comment]
When rendering `SonataUserBundle:Admin/Core:user_block.html.twig` (rendered by default in Sonata Admin) the code breaks while trying to get a nonexistent `id` of `Symfony\Component\Security\Core\User\User`.

Since in_memory provider always creates that object instance and we can't override it to add the `id` metadata, we can't fix it in configuration files.

Recommended solution:
in user_block.html.twig:L6 test if `sonata_user.userAdmin` supports the `app.user` class, if don't then we don't need a profile button.

As temporary solution you can override the template file with:
```yaml
sonata_admin:
    templates:
        user_block:           'SonataAdminBundle:Core:user_block.html.twig'
```
