### ISSUE TITLE
Symfony 3 compatibility

### ISSUE THREAD

**Issue by samuel4x4** [sonata-project/SonataUserBundle#724]
Hello, is there any plan regarding a new SonataUserBundle release for Symfony 3?

Thanks

**Comment by Soullivaneuh** [comment]
When FOSUserBundle 2.x will be stable and supported here.

See WIP here: https://github.com/sonata-project/SonataUserBundle/blob/add_support_for_fos_user2/composer.json

See also big changes issue here: https://github.com/sonata-project/SonataAdminBundle/issues/3731

**Comment by Soullivaneuh** [comment]
Ignore my last comment, I miss read your issue.

For the moment, I'm working on a new upgrade plan: https://github.com/sonata-project/SonataUserBundle/issues/730

After that, I'll happy to review/accept PRs for SF 3 support. :+1:

**Comment by Soullivaneuh** [comment]
Re-ignore my last-comment.

SF 3.0 is not supported because FOSUser 1.x does not support it.

FOSUser 2.x is not stable and is not supported by our bundle right now.

**Comment by saidinizar** [comment]
It is possible to use sonata 2.3 with symfony 3.1  ?
Thank you

**Comment by greg0ire** [comment]
I'm not sure, but we don't support Sonata 2 anymore, you should upgrade.

**Comment by saidinizar** [comment]
I tried with sonata 3 but I think it is not yet stable ?

**Comment by greg0ire** [comment]
Sonata 3 is stable.

**Comment by Artem-G** [comment]
Sonata Admin + Sonata User + FOS - this bunch prevents us from upgrading to Symfony 3
Any hint on when it may be upgraded?

**Comment by greg0ire** [comment]
Sonata Admin is compatible with sf3. Sonata won't be as long as FOS isn't in a stable version, b/c FOS is a dependency of Sonata User.

**Comment by Artem-G** [comment]
@greg0ire yes, I understand that Sonata Admin alone is compatible with SF3, but we can't upgrade to SF3 because of Sonata User + FOS works only in SF2. These two bundles prevent us from moving to SF3 from SF2. We're thinking either continue using SF2 (until Sonata Admin + Sonata User + FOS will work on SF3) or replacing FOS with the own authorization bundle. What would you recommend?

**Comment by greg0ire** [comment]
I'd recommend trying https://github.com/FriendsOfSymfony/FOSUserBundle/releases/tag/v2.0.0-beta1 and https://github.com/sonata-project/SonataUserBundle/tree/add_support_for_fos_user2 together to make your decision. If it's good enough, then maybe you can wait, otherwise just drop both bundles.

**Comment by vladim1** [comment]
If I am corrent there is still a loop of composer dependencies:
- We use symfony 3.*
- We have to use FOSUser 2.x, because FOSUser 1.3 (requires "symfony/framework-bundle": "~2.3") doesn't support symfony 3
- We have to use "sonata-project/user-bundle" : "dev-add_support_for_fos_user2" to use FOSUser 2.x
- "sonata-project/user-bundle" : "dev-add_support_for_fos_user2" requires "sonata-project/admin-bundle": "~2.3|~2.4@dev",
- "sonata-project/admin-bundle": "~2.3" dependes on "symfony/http-foundation": "~2.3". But we need 3.*
Am I right? Or what dependencies should I write in composer json to get symfony3 work with sonata user bundle?

**Comment by greg0ire** [comment]
> "sonata-project/user-bundle" : "dev-add_support_for_fos_user2" requires "sonata-project/admin-bundle": "~2.3|~2.4@dev",

It should depend on ^3.0, but since no one is contributing to that branch, it doesn't.

**Comment by vladim1** [comment]
@greg0ire Created a [PR](https://github.com/sonata-project/SonataUserBundle/pull/836) to handle this. 
Did anyone succeeded with using Sonata user bundle with Symfony 3?

**Comment by vitrus** [comment]
FOS/UserBundle 2.0 is currently stable. But even the @dev version of sonata-project/user-bundle still has the `symfony/security: ^2.3` requirement and will not work with Symfony3.

**Comment by jordisala1991** [comment]
https://github.com/sonata-project/SonataUserBundle/pull/869
