### ISSUE TITLE
Which version for friendsofsymfony/user-bundle dev-master / 2.0.x-dev ?

### ISSUE THREAD

**Issue by mathieubb** [sonata-project/SonataUserBundle#754]
Hello everyone,

Is there any version/branch for sonata-project/user-bundle to work with the version 2.0.x-dev of friendsofsymfony/user-bundle ???

My current composer.json looks like :
```
    "require": {
        ...
        "friendsofsymfony/user-bundle": "dev-master",
        "sonata-project/user-bundle": "3.x-dev",
        ...
    },
```

**Comment by Soullivaneuh** [comment]
FOSUser 2.x is not supported for the moment because it is not stable yet.

You can try this branch: https://github.com/sonata-project/SonataUserBundle/tree/add_support_for_fos_user2

But without *ANY* stability and official support.

You can also follow/help this PR: https://github.com/sonata-project/SonataUserBundle/pull/745
